### PR TITLE
Fixes for #39 and #47

### LINKED ISSUE #39: Expose configuration for private IP address in baremetal provider
When using baremetal provider, there should be option to configure also its private IP addresses as you might want to have defined some virtual network between nodes in the clouds and want to be able to access these addresses also when using bare provider. Or you just want to mimic with the baremetal provider the same public vs private IP address setup as when using some other cloud provider where public and private IP addresses are not equal.

### LINKED ISSUE #47: JClouds Docker provider moved out labs
The docker api is now in the main JClouds repo. Let's update the Sunstone dependencies.

### PR DESCRIPTION
**Pull request by kwart**
Fixes #39 and fixes #47

### CODE REVIEW

**Comment by Ladicek** [comment]
Looks good on the first sight.

**Comment by LittleJohnII** [comment]
Looks good to me, except for line 137, which we discussed in person. Another commit is probably comming.

**Comment by kwart** [comment]
The problematic test in fix for #39 was improved to check exit status.

Two more commits were added - mainly to cover also #42.

**Comment by LittleJohnII** [comment]
LGTM, merging.

**Pull request merged**
