### PR TITLE
fix for Azure-ARM installation

### PR DESCRIPTION
**Pull request by tplevko**
Adds the location property for the Azure ARM  - fixes the node initialization for Azure ARM provider.

### CODE REVIEW

**Comment by tplevko** [comment]
@LittleJohnII hi, seems like the travis-ci is not working correctly. This PR provides fix for the Azure-ARM provider, could you please have a look and provide some input? Thanks!

**Comment by kwart** [comment]
The #90 fixes Travis CI environmental issues.

**Comment by LittleJohnII** [comment]
The change looks good to me. I merged #90 and restarted CI.

**Comment by LittleJohnII** [comment]
Yeah, I think you'll need to rebase on top of #90 for this to work. Sorry about the inconvenience.

**Comment by LittleJohnII** [comment]
I'm not sure what the problem is:
```
$ echo -e "[Service]\nExecStart=\nExecStart=/usr/bin/dockerd -H fd:// -H tcp://127.0.0.1:2375" | sudo SYSTEMD_EDITOR=tee systemctl edit docker
Cannot edit units if not on a tty.
```
The same command works with PR #90 . I'm merging this, the changes look good.

**Pull request merged**
